import { Student, MemorizationRecord, ScheduleItem, AgendaItem, AnnouncementItem, PointCategory, PointRecord, TeacherAttendance } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 's1',
    name: 'Ahmad Fathanah',
    nisn: '0098765432',
    nis: 'NIS-2024001',
    nip: '0098765432',
    gender: 'Laki-laki',
    class: '10 IPA 1',
    program: 'Pondok',
    status: 'Aktif',
    dorm: 'Umar Bin Khattab',
    tahfidzJuz: 15,
    tahfidzDetail: 'Surah Al-Kahfi (50)',
    totalScore: 92.0,
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWm4KibatigPk2YlT4VSXuchCtAGmxn4rboR2upZPNUS_KrT-oNdadIaHBrvLzv3TjijYw3wHHerP4gUwuQcO7OOgvWY7SfUnMpw1iCO_2TP3L2Gm3YsXqdRmOWRxgsDoxO2ToruXaxrhbWfIwh8Z814Mx2uXq8IZPVa_qwOIPcv0fXdPLBg7klwYW8ENSObxGX2juxunP-LrC850vZB0HtUxW8KIroHw2WIUVGTBXrP32NyNWEg6g',
    attendanceRate: 98,
    latestAchievement: 'Juara 1 MTQ',
    dormRoom: 'Kamar 102',
    birthPlace: 'Cirebon',
    birthDate: '2010-04-12',
    parentName: 'H. Lukman Fathanah',
    phoneNumber: '081234567890',
    address: 'Jl. Pemuda No. 45, Kesambi, Cirebon',
    entryYear: '2024'
  },
  {
    id: 's2',
    name: 'Ahmad Rizqi Maulana',
    nisn: '0051234567',
    nis: 'NIS-2024002',
    nip: '101234567',
    gender: 'Laki-laki',
    class: '10 MIPA A',
    program: 'Pondok',
    status: 'Aktif',
    dorm: 'Asrama A-01',
    tahfidzJuz: 5,
    tahfidzDetail: "Al-Ma'idah (120)",
    totalScore: 88.5,
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCkLYXeLgpBsZWbBC8F6MHXFF40RID1YkqZxXrsP-H0Fbc2i6FRGU5MdMW47p6gSBNGUTFfcOxtK4ad4zdQb1uPKsU8QPZLRsw0N_eRN2nGl-jYeYqCnnYLH5ajiDH7hSrKl8YCSBLFTos7hWz65yS-Q6Pk7agAo3GUYYVPKihODvnjhD64eygg9QNugdZ4HPEsUlWvFJTOXyCv013c9pRr8AIf8RLXPJYoP9yC43dtDquPvx6b1Yyw',
    attendanceRate: 96,
    latestAchievement: 'Sertifikasi Juz 30',
    dormRoom: 'A-01',
    birthPlace: 'Bandung',
    birthDate: '2010-08-22',
    parentName: 'Sulaeman Maulana',
    phoneNumber: '081398765432',
    address: 'Jl. Dago No. 102, Coblong, Bandung',
    entryYear: '2024'
  },
  {
    id: 's3',
    name: 'Siti Aisyah Azzahra',
    nisn: '0051234568',
    nis: 'NIS-2024003',
    nip: '101234568',
    gender: 'Perempuan',
    class: '10 IPS B',
    program: 'Madrasah',
    status: 'Aktif',
    dorm: 'Asrama Khadijah',
    tahfidzJuz: 2,
    tahfidzDetail: 'Al-Baqarah (252)',
    totalScore: 92.0,
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUFjYUibwfoObiO0LkgtB7CwJJG9v24SRwrhxRKGKE4rAwYggU9vgvVU03CP9pxjtHvJM3iHfSJNcrDByFnuBmJl9AiJskOKhYoMRRgIf8iPyGko1z2XevqCwFMs2qORbNAwVfKufvGYf_CH4iJFMFc4TihK4gtw5YoGoqkdcRS9ziGvHYMT8TRxApI5qSn-qtcSZNTRpB8p5_pU-ISTj9_E0_Rl1-dQPFyn8hrs4nvkqe3A1ZDHZD',
    attendanceRate: 99,
    latestAchievement: 'Bintang Kelas',
    dormRoom: 'Kamar 3',
    birthPlace: 'Jakarta Selatan',
    birthDate: '2010-11-05',
    parentName: 'Hj. Aminah Azzahra',
    phoneNumber: '085712345678',
    address: 'Kebayoran Lama, Jakarta Selatan',
    entryYear: '2024'
  },
  {
    id: 's4',
    name: 'Fahmi Abdullah',
    nisn: '0031234569',
    nis: 'NIS-2023004',
    nip: '081234569',
    gender: 'Laki-laki',
    class: 'Lulusan 2023',
    program: 'Madrasah',
    status: 'Alumni',
    dorm: 'Angkatan 2020',
    tahfidzJuz: 30,
    tahfidzDetail: 'Sertifikat: Ya',
    totalScore: 89.2,
    photoUrl: '',
    initials: 'FA',
    attendanceRate: 95,
    birthPlace: 'Surabaya',
    birthDate: '2008-01-14',
    parentName: 'H. Abdullah Majid',
    phoneNumber: '081288889999',
    address: 'Gubeng, Surabaya',
    entryYear: '2023'
  },
  {
    id: 's5',
    name: 'Ahmad Zaki',
    nisn: '0098765411',
    nis: 'NIS-2024005',
    nip: '101234511',
    gender: 'Laki-laki',
    class: 'Kelas 11A',
    program: 'Pondok',
    status: 'Aktif',
    dorm: 'Umar Bin Khattab',
    tahfidzJuz: 28,
    tahfidzDetail: 'An-Nisa (40)',
    totalScore: 94.5,
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWhjtGPubSZtBX4d4XUrXAcaKh9ShVscQ84RfHAs0BRX3uyZT-lBwbbeWUrqxrZvb-iEpl_JgbR9aCXEOUCd1q99oy2YuiqJtjseq6g2eQc2fSJdxvzL3YrrpBn9_p-_PCPKzDCRCkTz5dgNV6rqQzRppjWtCo6dnada21Fj4YPDz7iQmmSZ15GSjrSzUXY0E4G6VQL_5AVGhMZ3JfJJyvAfeN4dd0WZ-5S46qbPX2tiQK-DdrAW0n',
    attendanceRate: 98,
    latestAchievement: 'Juara 2 Tahfidz 20 Juz',
    birthPlace: 'Semarang',
    birthDate: '2009-09-09',
    parentName: 'K.H. Ahmad Dahlan',
    phoneNumber: '082233445566',
    address: 'Tembalang, Semarang',
    entryYear: '2024'
  },
  {
    id: 's6',
    name: 'Fatimah Az-Zahra',
    nisn: '0098765422',
    nis: 'NIS-2024006',
    nip: '101234522',
    gender: 'Perempuan',
    class: 'Kelas 12B',
    program: 'Pondok',
    status: 'Aktif',
    dorm: 'Aisyah',
    tahfidzJuz: 27,
    tahfidzDetail: 'Ali Imran (100)',
    totalScore: 95.2,
    photoUrl: '',
    initials: 'FA',
    attendanceRate: 100,
    latestAchievement: 'Juara Harapan 1 MTQ Nasional',
    birthPlace: 'Yogyakarta',
    birthDate: '2008-12-12',
    parentName: 'Prof. Yunus Prasetyo',
    phoneNumber: '087766554433',
    address: 'Sleman, Yogyakarta',
    entryYear: '2024'
  },
  {
    id: 's7',
    name: 'Muhammad Ali',
    nisn: '0098765433',
    nis: 'NIS-2024007',
    nip: '101234533',
    gender: 'Laki-laki',
    class: 'Kelas 10A',
    program: 'Pondok',
    status: 'Aktif',
    dorm: 'Abu Bakar',
    tahfidzJuz: 25,
    tahfidzDetail: 'Al-Maidah (10)',
    totalScore: 91.8,
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0pR14mBgPAeiPCpYkfcH_pHBdPGzceWfXWDmgt_V45j073EVoQUw_W_dzEReI-0gzEB7EPskeHq6CjX2rYQPtqsR9hYdHwEaFe9devt1h_ZeIvyS-5_drwDZVu-ZDvCKk-ttDvyDeI7L6hQY2rKCvx_QTKQ9SjRTnODgWDcPDUaNijj3ZcN4H1uEGiAwbHdChtoCITYo4icDGTW83Myt8fGaCDyoD7vwP4d2asc7lr0DB1kkHGAsA',
    attendanceRate: 97,
    latestAchievement: 'Juara Lomba Kaligrafi',
    birthPlace: 'Solo',
    birthDate: '2010-01-01',
    parentName: 'Muhammad Hasan',
    phoneNumber: '081299001122',
    address: 'Laweyan, Solo',
    entryYear: '2024'
  },
  {
    id: 's8',
    name: 'Siti Aisyah',
    nisn: '0098765444',
    nis: 'NIS-2024008',
    nip: '101234544',
    gender: 'Perempuan',
    class: 'Kelas 11C',
    program: 'Madrasah',
    status: 'Aktif',
    dorm: 'Aisyah',
    tahfidzJuz: 22,
    tahfidzDetail: 'Al-An\'am (45)',
    totalScore: 89.5,
    photoUrl: '',
    initials: 'SA',
    attendanceRate: 96,
    birthPlace: 'Cianjur',
    birthDate: '2009-03-18',
    parentName: 'Dadan Hamdani',
    phoneNumber: '085211223344',
    address: 'Cipanas, Cianjur',
    entryYear: '2024'
  },
  {
    id: 's9',
    name: 'Umar Mukhtar',
    nisn: '0098765455',
    nis: 'NIS-2024009',
    nip: '101234555',
    gender: 'Laki-laki',
    class: 'Kelas 9A',
    program: 'Madrasah',
    status: 'Aktif',
    dorm: 'Ali Bin Abi Thalib',
    tahfidzJuz: 20,
    tahfidzDetail: 'Al-A\'raf (12)',
    totalScore: 90.1,
    photoUrl: '',
    initials: 'UM',
    attendanceRate: 98,
    birthPlace: 'Malang',
    birthDate: '2011-06-15',
    parentName: 'Muchtar Efendi',
    phoneNumber: '081122334455',
    address: 'Lowokwaru, Malang',
    entryYear: '2024'
  }
];

export const INITIAL_MEMORIZATION: MemorizationRecord[] = [
  {
    id: 'm1',
    studentId: 's1',
    studentName: 'Ahmad Fathanah',
    date: '2023-11-12',
    ustadz: 'Ust. Ahmad Baihaqi',
    type: 'Hafalan Baru (Ziyadah)',
    juz: 15,
    surah: 'Al-Kahfi',
    startAyat: 1,
    endAyat: 50,
    page: 293,
    line: '1-15',
    fluencyScore: 85,
    tajwidScore: 90,
    tartilScore: 88,
    notesChecklist: {
      makharijulHuruf: false,
      madConsistency: false,
      ghunnahHold: false
    },
    finalScore: 87.6,
    grade: 'A',
    predikat: 'Sangat Baik (Jayyid Jiddan)'
  },
  {
    id: 'm2',
    studentId: 's2',
    studentName: 'Ahmad Rizqi Maulana',
    date: '2024-05-15',
    ustadz: 'Ust. Ahmad Baihaqi',
    type: 'Hafalan Baru (Ziyadah)',
    juz: 5,
    surah: "Al-Ma'idah",
    startAyat: 1,
    endAyat: 40,
    page: 110,
    line: '1-15',
    fluencyScore: 88,
    tajwidScore: 89,
    tartilScore: 88,
    notesChecklist: {
      makharijulHuruf: false,
      madConsistency: true,
      ghunnahHold: false
    },
    finalScore: 88.3,
    grade: 'A',
    predikat: 'Sangat Baik (Jayyid Jiddan)'
  },
  {
    id: 'm3',
    studentId: 's3',
    studentName: 'Siti Aisyah Azzahra',
    date: '2024-05-14',
    ustadz: 'Ust. Abdullah',
    type: 'Hafalan Baru (Ziyadah)',
    juz: 2,
    surah: 'Al-Baqarah',
    startAyat: 200,
    endAyat: 252,
    page: 41,
    line: '1-15',
    fluencyScore: 91,
    tajwidScore: 93,
    tartilScore: 92,
    notesChecklist: {
      makharijulHuruf: false,
      madConsistency: false,
      ghunnahHold: false
    },
    finalScore: 92.0,
    grade: 'A',
    predikat: 'Istimewa (Mumtaz)'
  }
];

export const SCHEDULE_ITEMS: ScheduleItem[] = [
  {
    id: 'sc1',
    time: '04:30 - 06:00',
    title: 'Shalat Shubuh & Halaqah Pagi',
    location: 'Masjid Utama',
    icon: 'done',
    isPast: true
  },
  {
    id: 'sc2',
    time: '07:30 - 12:00',
    title: 'KBM Diniyah & Umum',
    location: 'Seluruh Kelas',
    icon: 'school',
    isCurrent: true
  },
  {
    id: 'sc3',
    time: '15:30 - 17:00',
    title: 'Setoran Tahfidz Sore',
    location: 'Gedung Tahfidz',
    icon: 'menu_book'
  },
  {
    id: 'sc4',
    time: '18:00 - 19:30',
    title: 'Shalat Maghrib & Taklim',
    location: 'Masjid Utama',
    icon: 'mosque'
  }
];

export const AGENDA_ITEMS: AgendaItem[] = [
  {
    id: 'ag1',
    title: 'Ujian Tahfidz Semester Genap',
    description: 'Persiapan pelaksanaan imtihan tahfidz untuk seluruh santri reguler dan takhassus.',
    date: '15 Agustus 2024',
    label: 'Penting'
  },
  {
    id: 'ag2',
    title: 'Rapat Wali Santri',
    description: 'Sosialisasi program kerja tahunan dan laporan perkembangan akademik santri.',
    date: '20 Agustus 2024',
    label: 'Informasi'
  },
  {
    id: 'ag3',
    title: 'Pendaftaran Santri Baru Gelombang 2',
    description: 'Pembukaan gelombang kedua untuk tingkat MTs dan MA secara online.',
    date: '1 September 2024',
    label: 'Kegiatan'
  }
];

export const ANNOUNCEMENT_ITEMS: AnnouncementItem[] = [
  {
    id: 'an1',
    title: 'Pembayaran SPP Semester Genap',
    content: 'Batas akhir pembayaran SPP semester genap adalah tanggal 25 bulan ini. Mohon segera diselesaikan untuk kelancaran administrasi.',
    date: '2 Hari yang lalu'
  },
  {
    id: 'an2',
    title: 'Jadwal Pengambilan Raport',
    content: 'Pengambilan raport sisipan akan dilaksanakan pada hari Jumat secara bergiliran untuk menghindari antrean panjang.',
    date: '1 Minggu yang lalu'
  }
];

export const SURAHS = [
  'Al-Baqarah',
  'Ali \'Imran',
  'An-Nisa\'',
  "Al-Ma'idah",
  'Al-An\'am',
  'Al-A\'raf',
  'Al-Anfal',
  'At-Taubah',
  'Yunus',
  'Hud',
  'Yusuf',
  'Ar-Ra\'d',
  'Ibrahim',
  'Al-Hijr',
  'An-Nahl',
  'Al-Isra\'',
  'Al-Kahfi',
  'Maryam',
  'Thaha',
  'Al-Anbiya\'',
  'Al-Hajj',
  'Al-Mu\'minun',
  'An-Nur',
  'Al-Furqan',
  'Asy-Syu\'ara\'',
  'An-Naml',
  'Al-Qashash',
  'Al-Ankabut',
  'Ar-Rum',
  'Luqman',
  'As-Sajdah',
  'Al-Ahzab',
  'Saba\'',
  'Fathir',
  'Yasin',
  'Ash-Shaffat',
  'Shad',
  'Az-Zumar',
  'Ghafir',
  'Fushshilat',
  'Asy-Syura',
  'Az-Zukhruf',
  'Ad-Dukhan',
  'Al-Jatsiyah',
  'Al-Ahqaf',
  'Muhammad',
  'Al-Fath',
  'Al-Hujurat',
  'Qaf',
  'Adz-Dzariyat',
  'At-Thur',
  'An-Najm',
  'Al-Qamar',
  'Ar-Rahman',
  'Al-Waqi\'ah',
  'Al-Hadid',
  'Al-Mujadilah',
  'Al-Hasyr',
  'Al-Mumtahanah',
  'Ash-Shaff',
  'Al-Jumu\'ah',
  'Al-Munafiqun',
  'At-Taghabun',
  'At-Thalaq',
  'At-Tahrim',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Haqqah',
  'Al-Ma\'arij',
  'Nuh',
  'Al-Jin',
  'Al-Muzzammil',
  'Al-Muddatstsir',
  'Al-Qiyamah',
  'Al-Insan',
  'Al-Mursalat',
  'An-Naba\'',
  'An-Nazi\'at',
  '\'Abasa',
  'At-Takwir',
  'Al-Infithar',
  'Al-Muthaffifin',
  'Al-Insyiqaq',
  'Al-Buruj',
  'At-Thariq',
  'Al-A\'la',
  'Al-Ghasyiyah',
  'Al-Fajr',
  'Al-Balad',
  'Asy-Syams',
  'Al-Lail',
  'Ad-Dhuha',
  'Asy-Syarh',
  'At-Tin',
  'Al-\'Alaq',
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  'Al-\'Adiyat',
  'Al-Qari\'ah',
  'At-Takatsur',
  'Al-\'Ashr',
  'Al-Humazah',
  'Al-Fil',
  'Quraisy',
  'Al-Ma\'un',
  'Al-Kautsar',
  'Al-Kafirun',
  'An-Nashr',
  'Al-Lahab',
  'Al-Ikhlash',
  'Al-Falaq',
  'An-Nas'
];

export const CLASSES = [
  'Semua Kelas',
  '10 IPA 1',
  '10 MIPA A',
  '10 IPS B',
  '11 MIPA A',
  '11A',
  '11C',
  '12B',
  '9A'
];

export const PROGRAMS = [
  'Semua Program',
  'Pondok',
  'Madrasah'
];

export const SECTIONS = [
  'Semua Angkatan',
  'Angkatan 2023',
  'Angkatan 2022',
  'Angkatan 2021',
  'Angkatan 2020'
];

export const USTADZ_LIST = [
  'Ust. Ahmad Baihaqi',
  'Ust. Abdullah',
  'Ustadzah Fatimah',
  'Ust. Muhammad Yusuf',
  'Ust. Ali Ridho',
  'Ustadzah Sarah'
];

export const INITIAL_TEACHER_ATTENDANCE: TeacherAttendance[] = [
  { id: 'ta1', teacherName: 'Ust. Ahmad Baihaqi', date: '2026-07-07', status: 'Hadir', timeIn: '06:45', timeOut: '14:30', notes: 'Mengajar kelas pagi' },
  { id: 'ta2', teacherName: 'Ust. Abdullah', date: '2026-07-07', status: 'Hadir', timeIn: '07:12', timeOut: '15:00', notes: 'Tepat waktu' },
  { id: 'ta3', teacherName: 'Ustadzah Fatimah', date: '2026-07-07', status: 'Hadir', timeIn: '07:05', timeOut: '14:45', notes: 'Mengajar Nahwu' },
  { id: 'ta4', teacherName: 'Ust. Muhammad Yusuf', date: '2026-07-07', status: 'Izin', notes: 'Ada keperluan keluarga di luar kota' },
  { id: 'ta5', teacherName: 'Ust. Ali Ridho', date: '2026-07-07', status: 'Hadir', timeIn: '06:58', notes: 'Piket Masjid' },
  { id: 'ta6', teacherName: 'Ustadzah Sarah', date: '2026-07-07', status: 'Sakit', notes: 'Demam tinggi' }
];

export const INITIAL_TEACHING_JOURNALS = [
  { id: 'tj1', teacherName: 'Ust. Ahmad Baihaqi', subject: 'Aqidah Akhlaq', class: '10 IPA 1', date: '2026-07-06', topic: 'Bab Tauhid dan Ma\'rifatullah', presentStudents: 28, totalStudents: 30, notes: 'Santri sangat antusias mengikuti materi.' },
  { id: 'tj2', teacherName: 'Ust. Abdullah', subject: 'Fiqih Ibadah', class: '10 MIPA A', date: '2026-07-06', topic: 'Thaharah (Wudhu dan tayamum)', presentStudents: 25, totalStudents: 25, notes: 'Praktek tayamum berjalan lancar.' },
  { id: 'tj3', teacherName: 'Ustadzah Fatimah', subject: 'Bahasa Arab (Nahwu)', class: '10 IPS B', date: '2026-07-05', topic: 'Isim, Fi\'il, dan Harf', presentStudents: 23, totalStudents: 24, notes: 'Satu santri izin sakit.' }
];

export const INITIAL_POINT_CATEGORIES: PointCategory[] = [
  { id: 'pc1', type: 'Pelanggaran', name: 'Terlambat Berjamaah', points: -5 },
  { id: 'pc2', type: 'Pelanggaran', name: 'Tidak Piket Kelas', points: -10 },
  { id: 'pc3', type: 'Pelanggaran', name: 'Keluar Tanpa Izin', points: -25 },
  { id: 'pc4', type: 'Pelanggaran', name: 'Membawa HP / Gadget Ilegal', points: -50 },
  { id: 'pc5', type: 'Pelanggaran', name: 'Melanggar Aturan Berpakaian', points: -5 },
  { id: 'pc6', type: 'Prestasi', name: 'Khatam Al-Quran', points: 50 },
  { id: 'pc7', type: 'Prestasi', name: 'Hafal 1 Juz Baru', points: 30 },
  { id: 'pc8', type: 'Prestasi', name: 'Juara Kelas / Lomba', points: 40 },
  { id: 'pc9', type: 'Prestasi', name: 'Piket Mandiri / Sukarela', points: 10 },
  { id: 'pc10', type: 'Prestasi', name: 'Membantu Ustadz', points: 15 }
];

export const INITIAL_POINT_RECORDS: PointRecord[] = [
  { id: 'pr1', studentId: 's1', studentName: 'Ahmad Fathanah', class: '10 IPA 1', date: '2026-07-06', type: 'Prestasi', categoryName: 'Hafal 1 Juz Baru', points: 30, notes: 'Menyelesaikan setoran juz 15 dengan sangat baik', teacherName: 'Ust. Ahmad Baihaqi' },
  { id: 'pr2', studentId: 's2', studentName: 'Ahmad Rizqi Maulana', class: '10 MIPA A', date: '2026-07-05', type: 'Pelanggaran', categoryName: 'Terlambat Berjamaah', points: -5, notes: 'Terlambat shalat Subuh berjamaah', teacherName: 'Ust. Abdullah' },
  { id: 'pr3', studentId: 's3', studentName: 'Siti Aisyah Azzahra', class: '10 IPS B', date: '2026-07-05', type: 'Prestasi', categoryName: 'Juara Kelas / Lomba', points: 40, notes: 'Juara 1 Lomba Pidato Bahasa Arab', teacherName: 'Ustadzah Fatimah' },
  { id: 'pr4', studentId: 's5', studentName: 'Ahmad Zaki', class: 'Kelas 11A', date: '2026-07-04', type: 'Pelanggaran', categoryName: 'Melanggar Aturan Berpakaian', points: -5, notes: 'Tidak memakai peci saat KBM', teacherName: 'Ust. Ali Ridho' }
];

